### ISSUE TITLE
Feedback Wiki and Sprint Goal

### ISSUE THREAD

**Issue by scharffc** [paceuniversity/CS3892016team5#19]
@iancarv @elazimi @brayank

The wiki and the sprint goal are well done.

**Wiki**

Please re-organize the menu on the right.

What is Questionnaire?

Add the tools, even the communication tools in the tools section

**Sprint goal**

Please add Sprint 1 as label for all issues related to sprint1.

Be sure to put comments to the issues during the process. We want to be able to monitor your work.

I know you do it in Slack but put some comments there too. This will help with the burndown chart.

**Comment by elazimi** [comment]
Complete
