### ISSUE TITLE
Sprint 1

### ISSUE THREAD

**Issue by scharffc** [paceuniversity/CS3892016team5#29]
Wiki

The wiki needs to be reorganized. I cannot go directly to sprint 1 and access the scrums, retro and so on. I cannot access the video either.

Scrums

I cannot access the scrums. Where are they? Please let me know.

Demo

The demo was good.

Installation of the app

Please let me know the next step

Contributions

It is important to see more contributions from different team members. 
https://github.com/paceuniversity/CS3892016team5/graphs/contributors

Retrospective

Great that you have so many stats.

@iancarv @elazimi @brayank @briex

**Comment by elazimi** [comment]
@scharffc  Will update by end of tonight. Also, to view the video, go to Homepage -> Demos -> "View Raw" as the video file is 40 megabytes.
